<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Ploch.CommandLine.Spectre.SampleApp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ploch.CommandLine.Spectre" />
    <PackageReference Include="Ploch.CommandLine.Spectre.FluentValidation" />
    <PackageReference Include="Ploch.CommandLine.Spectre.Serilog" />
    <PackageReference Include="Ploch.CommandLine.UseCases" />
    <PackageReference Include="Ploch.Common" />
    <PackageReference Include="Ploch.Common.DependencyInjection" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Cli" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Ardalis.Result" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
